### ISSUE TITLE
Erro ao rodar o server do front. 

### ISSUE THREAD

**Issue by pedrophfsdev** [glaucia86/frontend-vue-starter-app#1]
Olá, Glaucia!

Fiz o processo indicado e ao tentar rodar o "npm run serve" aparece o seguinte erro. Seria a versão do Node? Qual está sendo usada no projeto?

"$ npm run serve

> client@0.1.0 serve
> npm run lint-fix && vue-cli-service serve

> client@0.1.0 lint-fix
> npm run lint --fix

> client@0.1.0 lint
> vue-cli-service lint

 DONE  No lint errors found!
 INFO  Starting development server...
<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active
<s> [webpack.Progress] 10% building 0/1 modules 1 active multi C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack-dev-server\client\index.js?http://localhost:8080&sockPath=/sockjs-node C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\hot\dev-server.js ./src/main.js
<s> [webpack.Progress] 10% building 1/1 modules 0 active
<s> [webpack.Progress] 10% building 1/1 modules 0 active
<s> [webpack.Progress] 10% building 1/2 modules 1 active multi C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\hot\dev-server.js C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack-dev-server\client\index.js?http://localhost:8080&sockPath=/sockjs-node ./src/main.js
<s> [webpack.Progress] 10% building 2/2 modules 0 active
(node:11120) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
<s> [webpack.Progress] 10% building 2/3 modules 1 active C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack-dev-server\client\index.js?http://localhost:8080&sockPath=/sockjs-node
<s> [webpack.Progress] 10% building 2/4 modules 2 active C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\hot\dev-server.js
<s> [webpack.Progress] 10% building 2/5 modules 3 active C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\cache-loader\dist\cjs.js??ref--12-0!C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\babel-loader\lib\index.js!C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\eslint-loader\index.js??ref--13-0!C:\Front-end-Vue\frontend-vue-starter-app\client\src\main.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Front-end-Vue\frontend-vue-starter-app\client\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.0.0"

**Comment by Jennsilva** [comment]
Olá, iniciei o curso e enfrento o mesmo problema que o do Pedro.
Gostaria de saber se o problema foi resolvido.
